# coding: utf-8

"""
    XigniteFactSetFundamentals

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_company_fundamentals_company import AllOfCompanyFundamentalsCompany  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfCompanyFundamentalsCompany(unittest.TestCase):
    """AllOfCompanyFundamentalsCompany unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfCompanyFundamentalsCompany(self):
        """Test AllOfCompanyFundamentalsCompany"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_company_fundamentals_company.AllOfCompanyFundamentalsCompany()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
