# coding: utf-8

"""
    XigniteFactSetFundamentals

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_company_balance_sheet_company import AllOfCompanyBalanceSheetCompany  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfCompanyBalanceSheetCompany(unittest.TestCase):
    """AllOfCompanyBalanceSheetCompany unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfCompanyBalanceSheetCompany(self):
        """Test AllOfCompanyBalanceSheetCompany"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_company_balance_sheet_company.AllOfCompanyBalanceSheetCompany()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
