# coding: utf-8

"""
    XigniteFactSetFundamentals

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.xignite_fact_set_fundamentals_api import XigniteFactSetFundamentalsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestXigniteFactSetFundamentalsApi(unittest.TestCase):
    """XigniteFactSetFundamentalsApi unit test stubs"""

    def setUp(self):
        self.api = XigniteFactSetFundamentalsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_x_fact_set_fundamentals_get_balance_sheets_get(self):
        """Test case for x_fact_set_fundamentals_get_balance_sheets_get

        """
        pass

    def test_x_fact_set_fundamentals_get_cash_flow_statements_get(self):
        """Test case for x_fact_set_fundamentals_get_cash_flow_statements_get

        """
        pass

    def test_x_fact_set_fundamentals_get_financial_statements_get(self):
        """Test case for x_fact_set_fundamentals_get_financial_statements_get

        """
        pass

    def test_x_fact_set_fundamentals_get_fundamentals_daily_range_get(self):
        """Test case for x_fact_set_fundamentals_get_fundamentals_daily_range_get

        """
        pass

    def test_x_fact_set_fundamentals_get_fundamentals_fiscal_range_get(self):
        """Test case for x_fact_set_fundamentals_get_fundamentals_fiscal_range_get

        """
        pass

    def test_x_fact_set_fundamentals_get_fundamentals_get(self):
        """Test case for x_fact_set_fundamentals_get_fundamentals_get

        """
        pass

    def test_x_fact_set_fundamentals_get_income_statements_get(self):
        """Test case for x_fact_set_fundamentals_get_income_statements_get

        """
        pass

    def test_x_fact_set_fundamentals_get_latest_fundamentals_get(self):
        """Test case for x_fact_set_fundamentals_get_latest_fundamentals_get

        """
        pass

    def test_x_fact_set_fundamentals_list_companies_get(self):
        """Test case for x_fact_set_fundamentals_list_companies_get

        """
        pass

    def test_x_fact_set_fundamentals_list_exchanges_by_region_get(self):
        """Test case for x_fact_set_fundamentals_list_exchanges_by_region_get

        """
        pass

    def test_x_fact_set_fundamentals_list_exchanges_get(self):
        """Test case for x_fact_set_fundamentals_list_exchanges_get

        """
        pass

    def test_x_fact_set_fundamentals_list_fundamentals_by_data_group_get(self):
        """Test case for x_fact_set_fundamentals_list_fundamentals_by_data_group_get

        """
        pass

    def test_x_fact_set_fundamentals_list_fundamentals_get(self):
        """Test case for x_fact_set_fundamentals_list_fundamentals_get

        """
        pass

    def test_x_fact_set_fundamentals_list_sectors_and_industries_get(self):
        """Test case for x_fact_set_fundamentals_list_sectors_and_industries_get

        """
        pass

    def test_x_fact_set_fundamentals_search_fundamentals_get(self):
        """Test case for x_fact_set_fundamentals_search_fundamentals_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
