# coding: utf-8

"""
    XigniteFactSetFundamentals

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.all_of_financial_statement_statement_type import AllOfFinancialStatementStatementType  # noqa: E501
from swagger_client.rest import ApiException


class TestAllOfFinancialStatementStatementType(unittest.TestCase):
    """AllOfFinancialStatementStatementType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfFinancialStatementStatementType(self):
        """Test AllOfFinancialStatementStatementType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.all_of_financial_statement_statement_type.AllOfFinancialStatementStatementType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
