# coding: utf-8

"""
    XigniteFactSetFundamentals

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CompanyIncomeStatement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'company': 'AllOfCompanyIncomeStatementCompany',
        'income_statement': 'AllOfCompanyIncomeStatementIncomeStatement'
    }

    attribute_map = {
        'company': 'Company',
        'income_statement': 'IncomeStatement'
    }

    def __init__(self, company=None, income_statement=None):  # noqa: E501
        """CompanyIncomeStatement - a model defined in Swagger"""  # noqa: E501
        self._company = None
        self._income_statement = None
        self.discriminator = None
        if company is not None:
            self.company = company
        if income_statement is not None:
            self.income_statement = income_statement

    @property
    def company(self):
        """Gets the company of this CompanyIncomeStatement.  # noqa: E501


        :return: The company of this CompanyIncomeStatement.  # noqa: E501
        :rtype: AllOfCompanyIncomeStatementCompany
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this CompanyIncomeStatement.


        :param company: The company of this CompanyIncomeStatement.  # noqa: E501
        :type: AllOfCompanyIncomeStatementCompany
        """

        self._company = company

    @property
    def income_statement(self):
        """Gets the income_statement of this CompanyIncomeStatement.  # noqa: E501


        :return: The income_statement of this CompanyIncomeStatement.  # noqa: E501
        :rtype: AllOfCompanyIncomeStatementIncomeStatement
        """
        return self._income_statement

    @income_statement.setter
    def income_statement(self, income_statement):
        """Sets the income_statement of this CompanyIncomeStatement.


        :param income_statement: The income_statement of this CompanyIncomeStatement.  # noqa: E501
        :type: AllOfCompanyIncomeStatementIncomeStatement
        """

        self._income_statement = income_statement

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompanyIncomeStatement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompanyIncomeStatement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
