# coding: utf-8

"""
    XigniteFactSetFundamentals

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExchangeList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'exchange_descriptions': 'list[ExchangeDescription]'
    }

    attribute_map = {
        'exchange_descriptions': 'ExchangeDescriptions'
    }

    def __init__(self, exchange_descriptions=None):  # noqa: E501
        """ExchangeList - a model defined in Swagger"""  # noqa: E501
        self._exchange_descriptions = None
        self.discriminator = None
        if exchange_descriptions is not None:
            self.exchange_descriptions = exchange_descriptions

    @property
    def exchange_descriptions(self):
        """Gets the exchange_descriptions of this ExchangeList.  # noqa: E501


        :return: The exchange_descriptions of this ExchangeList.  # noqa: E501
        :rtype: list[ExchangeDescription]
        """
        return self._exchange_descriptions

    @exchange_descriptions.setter
    def exchange_descriptions(self, exchange_descriptions):
        """Sets the exchange_descriptions of this ExchangeList.


        :param exchange_descriptions: The exchange_descriptions of this ExchangeList.  # noqa: E501
        :type: list[ExchangeDescription]
        """

        self._exchange_descriptions = exchange_descriptions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExchangeList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExchangeList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
