# coding: utf-8

"""
    XigniteFactSetFundamentals

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExchangeDescription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'market_identification_code': 'str',
        'market': 'str',
        'region': 'str'
    }

    attribute_map = {
        'market_identification_code': 'MarketIdentificationCode',
        'market': 'Market',
        'region': 'Region'
    }

    def __init__(self, market_identification_code=None, market=None, region=None):  # noqa: E501
        """ExchangeDescription - a model defined in Swagger"""  # noqa: E501
        self._market_identification_code = None
        self._market = None
        self._region = None
        self.discriminator = None
        if market_identification_code is not None:
            self.market_identification_code = market_identification_code
        if market is not None:
            self.market = market
        if region is not None:
            self.region = region

    @property
    def market_identification_code(self):
        """Gets the market_identification_code of this ExchangeDescription.  # noqa: E501


        :return: The market_identification_code of this ExchangeDescription.  # noqa: E501
        :rtype: str
        """
        return self._market_identification_code

    @market_identification_code.setter
    def market_identification_code(self, market_identification_code):
        """Sets the market_identification_code of this ExchangeDescription.


        :param market_identification_code: The market_identification_code of this ExchangeDescription.  # noqa: E501
        :type: str
        """

        self._market_identification_code = market_identification_code

    @property
    def market(self):
        """Gets the market of this ExchangeDescription.  # noqa: E501


        :return: The market of this ExchangeDescription.  # noqa: E501
        :rtype: str
        """
        return self._market

    @market.setter
    def market(self, market):
        """Sets the market of this ExchangeDescription.


        :param market: The market of this ExchangeDescription.  # noqa: E501
        :type: str
        """

        self._market = market

    @property
    def region(self):
        """Gets the region of this ExchangeDescription.  # noqa: E501


        :return: The region of this ExchangeDescription.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this ExchangeDescription.


        :param region: The region of this ExchangeDescription.  # noqa: E501
        :type: str
        """

        self._region = region

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExchangeDescription, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExchangeDescription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
