# coding: utf-8

"""
    XigniteFactSetFundamentals

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FundamentalDescription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'name': 'str',
        'value_type': 'str',
        'unit': 'str',
        'description': 'str',
        'source': 'str',
        'data_group': 'str'
    }

    attribute_map = {
        'type': 'Type',
        'name': 'Name',
        'value_type': 'ValueType',
        'unit': 'Unit',
        'description': 'Description',
        'source': 'Source',
        'data_group': 'DataGroup'
    }

    def __init__(self, type=None, name=None, value_type=None, unit=None, description=None, source=None, data_group=None):  # noqa: E501
        """FundamentalDescription - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._name = None
        self._value_type = None
        self._unit = None
        self._description = None
        self._source = None
        self._data_group = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if name is not None:
            self.name = name
        if value_type is not None:
            self.value_type = value_type
        if unit is not None:
            self.unit = unit
        if description is not None:
            self.description = description
        if source is not None:
            self.source = source
        if data_group is not None:
            self.data_group = data_group

    @property
    def type(self):
        """Gets the type of this FundamentalDescription.  # noqa: E501


        :return: The type of this FundamentalDescription.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this FundamentalDescription.


        :param type: The type of this FundamentalDescription.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def name(self):
        """Gets the name of this FundamentalDescription.  # noqa: E501


        :return: The name of this FundamentalDescription.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FundamentalDescription.


        :param name: The name of this FundamentalDescription.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def value_type(self):
        """Gets the value_type of this FundamentalDescription.  # noqa: E501


        :return: The value_type of this FundamentalDescription.  # noqa: E501
        :rtype: str
        """
        return self._value_type

    @value_type.setter
    def value_type(self, value_type):
        """Sets the value_type of this FundamentalDescription.


        :param value_type: The value_type of this FundamentalDescription.  # noqa: E501
        :type: str
        """

        self._value_type = value_type

    @property
    def unit(self):
        """Gets the unit of this FundamentalDescription.  # noqa: E501


        :return: The unit of this FundamentalDescription.  # noqa: E501
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this FundamentalDescription.


        :param unit: The unit of this FundamentalDescription.  # noqa: E501
        :type: str
        """

        self._unit = unit

    @property
    def description(self):
        """Gets the description of this FundamentalDescription.  # noqa: E501


        :return: The description of this FundamentalDescription.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this FundamentalDescription.


        :param description: The description of this FundamentalDescription.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def source(self):
        """Gets the source of this FundamentalDescription.  # noqa: E501


        :return: The source of this FundamentalDescription.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this FundamentalDescription.


        :param source: The source of this FundamentalDescription.  # noqa: E501
        :type: str
        """

        self._source = source

    @property
    def data_group(self):
        """Gets the data_group of this FundamentalDescription.  # noqa: E501


        :return: The data_group of this FundamentalDescription.  # noqa: E501
        :rtype: str
        """
        return self._data_group

    @data_group.setter
    def data_group(self, data_group):
        """Sets the data_group of this FundamentalDescription.


        :param data_group: The data_group of this FundamentalDescription.  # noqa: E501
        :type: str
        """

        self._data_group = data_group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FundamentalDescription, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FundamentalDescription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
